OCEAN/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.views.static import serve
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('baseinfo/',include('partsInfo.urls')),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

partsInfo/urls.py
from django.urls import path
from . import views

app_name = 'partsinfo'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('part_list/', views.parts_list, name='part_list'),
    path('add_parts_info/', views.add_parts_info, name='add_parts_info'),
    path('delete_parts_info/', views.delete_parts_info, name='delete_parts_info'),
    path('update_parts_info/', views.update_parts_info, name='update_parts_info'),

    path('factory_list/', views.factory_list, name='factory_list'),
    path('add_factory_info/', views.add_factory_info, name='add_factory_info'),
    path("delete_factory_info/", views.delete_factory_info, name='delete_factory_info'),
    path('update_factory_info/', views.update_factory_info, name='update_factory_info'),

    path('customer_list/', views.customer_list, name='customer_list'),
    path('add_customer_info/', views.add_customer_info, name='add_customer_info'),
    path('delete_customer_info/', views.delete_customer_info, name='delete_customer_info'),
    path('update_customer_info/', views.update_customer_info, name='update_customer_info'),

    path('factory_price_list/', views.factory_price_list, name='factory_price_list'),
    path('delete_factory_price/', views.delete_factory_price, name='delete_factory_price'),
    path('update_factory_price/', views.update_factory_price, name='update_factory_price'),
    path('add_factory_price/', views.add_factory_price, name='add_factory_price'),

    path('customer_price_list/', views.customer_price_list, name='customer_price_list'),
    path('delete_customer_price/', views.delete_customer_price, name='delete_customer_price'),
    path('update_customer_price/', views.update_customer_price, name='update_customer_price'),
    path('add_customer_price/', views.add_customer_price, name='add_customer_price'),

    path('factory_detail/<pk>', views.factory_detail, name='factory_detail'),
    path('customer_detail/<pk>', views.customer_detail, name='customer_detail'),
    path('part_detail/<pk>', views.part_detail, name='part_detail'),

    path('volume_data/', views.volume_data, name='volume_data'),
    path('add_volume_data/', views.add_volume_data, name='add_volume_data'),
    path('delete_volume_data/', views.delete_volume_data, name='delete_volume_data'),
    path('update_volume_data/', views.update_volume_data, name='update_volume_data'),

    path('add_ex_ome/',views.add_ex_ome,name='add_ex_ome'),
]

templates/partinfo/customer_list.html
{% extends 'partinfo/base.html' %}

{% load staticfiles %}
{% block menu_baseinfo %}active menu-open{% endblock %}
{% block menu_customer_list %}active{% endblock %}
{% block title %}客户列表{% endblock %}
{% block content-header %}客户信息{% endblock %}
{% block content %}
    <div class="row">

        <div class="col-md-12">

            <div class="box box-widget">
                <div class="box-body box-profile">
                    <div class="col-md-1 ">
                        <button type="button" class="btn btn-default" data-toggle="modal"
                                data-target="#model_customer_add"><i class="fa fa-plus"> 添加</i></button>
                    </div>

                    <div class="col-md-6 pull-right">
                        <div class="input-group">
                                <span class="input-group-btn">
                              <div id="btn_search_txt_clear" class="btn btn-default btn-flat"><i
                                      class="fa fa-close"></i> </div>
                              </span>
                            <input type="text" id="search_key_word" name="search_key_word" placeholder="查询条件....."
                                   class="form-control">
                            <span class="input-group-btn">
                              <div class="btn btn-default btn-flat" id="btn_search"><i
                                      class="fa fa-search"></i> </div>
                              </span>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>

            <div class="row" id="customer_list">

            </div>

            <div id="customer_list_bar">
                {% include 'partinfo/page_bar.html' %}
            </div>
        </div>
    </div>
    <div class="modal fade" id="model_customer_add" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">添加信息</h4>
                </div>
                <div class="modal-body">

                    <form action="#" method="post" id="add_customer_form">
                        {% csrf_token %}

                        <div class="col-md-6">
                            <div class="form-group">
                                <label>客户编号</label>
                                <input type="text" class="form-control" name="txt_customer_nick_name"
                                       id="txt_customer_nick_name"
                                       placeholder="">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>客户姓名</label>
                                <input type="text" class="form-control" name="txt_customer_name" id="txt_customer_name"
                                       placeholder="">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>描述</label>
                                <textarea class="form-control" rows="4" name="txt_area_customer_desc"
                                          id="txt_area_customer_desc"
                                          placeholder="....."></textarea>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>上传头像</label>
                                <input type="file" name="file_customer_icon" id="file_customer_icon">

                                <p class="help-block">图片格式BMP、JPG、JPEG、PNG、GIF</p>
                            </div>
                        </div>
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" id="btn_customer_cancel"
                            data-dismiss="modal">
                        <i class="fa fa-remove "> 取消</i></button>
                    <button type="submit" class="btn btn-primary" id="btn_customer_save"><i class="fa fa-check"> 保存</i>
                    </button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>


{% endblock %}
{% block javascript %}
    <script src="{% static 'js/parts_factory_customer_model_select2.js' %}"></script>

    <script>
        $(document).ready(function () {

            getPageInfo(1);

            $("#btn_search").click(function () {
                getPageInfo(1);
            })
            $("#btn_search_txt_clear").click(function () {
                $("#search_key_word").val("");
                getPageInfo(1);
            })

            $("#btn_customer_save").click(function () {
                var txt_customer_nick_name = $("#txt_customer_nick_name");
                if (txt_customer_nick_name.val() == "") {
                    txt_customer_nick_name.parent().addClass("has-error");
                    toastr.error('客户编号不能为空！');
                    return;
                }
                var file_customer_icon = $("#file_customer_icon");
                if (file_customer_icon.val() != '' && check_file_name_img(file_customer_icon.val())) {
                    toastr.error('请检查图片格式（格式BMP、JPG、JPEG、PNG、GIF等）!');
                    file_customer_icon.parent().addClass("has-error")
                    return;
                }
                var add_customer_form = new FormData($("#add_customer_form")[0])

                $.ajax({
                    type: "POST",
                    url: "{% url 'partsinfo:add_customer_info' %}",
                    data: add_customer_form,
                    async: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {


                        if (data == "success") {
                            $('#model_customer_add').modal('hide');
                            toastr.success('添加成功！2333');
                            getPageInfo(1);
                        } else if (data == 'info_exist') {

                            toastr.error('客户信息重复');
                            $("#txt_customer_nick_name").parent().addClass("has-error");
                        }
                        else {
                            toastr.error('添加失败 未知错误');
                        }

                    }

                });


            });

            $('#model_customer_add').on('hide.bs.modal', function () {

                $("#add_customer_form")[0].reset();

                var txt_customer_nick_name = $("#txt_customer_nick_name");
                if (txt_customer_nick_name.parent().hasClass("has-error")) {
                    txt_customer_nick_name.parent().removeClass("has-error");

                }
                var file_customer_icon = $("#file_customer_icon");

                if (file_customer_icon.parent().hasClass("has-error")) {
                    file_customer_icon.parent().removeClass("has-error");

                }

            });

        })


        function getPageInfo(page) {
            $.ajax({
                type: "GET",

                url: "{% url 'partsinfo:customer_list' %}?page=" + page+"&q="+$("#search_key_word").val(),

                async: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    showPartInfo(data.customer_list);
                    initPageBar(data.page_info, "customer_list_bar", 'getPageInfo');


                }

            });
        }

        function showPartInfo(data) {

            var customer_list = $('#customer_list');
            customer_list.empty();
            for (var index in data) {
                var html = '<div class="col-md-3 col-sm-6 col-xs-12">\n' +
                    '<a style="color: #444;"  href="/baseinfo/customer_detail/' + data[index].pk + '"><div class="box box-widget widget-user-2">\n' +
                    '                        <div class="widget-user-header">\n' +
                    '                            <div class="widget-user-image">\n' +
                    '                                <img class="img-circle" style="height: 65px" src="/media/' + data[index].fields.icon_img + '">\n' +
                    '                            </div>\n' +
                    '                            <h3 class="widget-user-username" style="display: block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">' + data[index].fields.nick_name + '</h3>\n' +
                    '                            <h5 class="widget-user-desc" style="display: block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">' + data[index].fields.name + '</h5>\n' +
                    '                        </div>\n' +
                    '                    </div></a>\n' +
                    '                </div>';

                customer_list.append(html);

            }


        }
    </script>

{% endblock %}

templates/partinfo/factory_list.html
{% extends 'partinfo/base.html' %}

{% load staticfiles %}
{% block menu_baseinfo %}active menu-open{% endblock %}
{% block menu_factory_list %}active{% endblock %}
{% block title %}工厂列表{% endblock %}
{% block content-header %}工厂信息{% endblock %}
{% block content %}

    <div class="row">

        <div class="col-md-12">

            <div class="box box-widget">
                <div class="box-body box-profile">
                    <div class="col-md-1 ">
                        <button type="button" class="btn btn-default" data-toggle="modal"
                                data-target="#model_factory_add"><i class="fa fa-plus"> 添加</i></button>
                    </div>

                    <div class="col-md-6 pull-right">

                        <div class="input-group">
                                <span class="input-group-btn">
                              <div id="btn_search_txt_clear" class="btn btn-default btn-flat"><i
                                      class="fa fa-close"></i> </div>
                              </span>
                            <input type="text" id="search_key_word" name="search_key_word" placeholder="查询条件....."
                                   class="form-control">
                            <span class="input-group-btn">
                              <div class="btn btn-default btn-flat" id="btn_search"><i
                                      class="fa fa-search"></i> </div>
                              </span>
                        </div>

                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <div class="row" id="factory_list">
                {#                <div class="col-md-3 col-sm-6 col-xs-12">#}
                {#                    <div class="box box-widget">#}
                {#                        <div class="box-header with-border">#}
                {#                            <span class="info-box-text" style="font-size:16px;">河间市久久机电有限公司</span>#}
                {#                            <div class="box-tools">#}
                {#                                <button type="button" class="btn btn-box-tool" data-widget="remove"><i#}
                {#                                        class="fa fa-times"></i></button>#}
                {#                            </div>#}
                {#                        </div>#}
                {#                        <div class="box-body">#}
                {#                            <div class="">#}
                {#                                <span class="text-muted"><i class="fa fa-users"></i> 张先生</span>#}
                {#                            </div>#}
                {#                            <div>#}
                {#                                <span class="text-muted"#}
                {#                                      style="display: block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;"><i#}
                {#                                        class="fa fa-tags"></i> 瑞安市塘下镇下湾村呈祥路35号</span>#}
                {#                            </div>#}
                {#                            <div>#}
                {#                                <span class="text-muted pull-left"><i class="fa fa-qq"></i> 909614012</span>#}
                {#                                <span class="text-muted pull-right"><i#}
                {#                                        class="fa fa-phone-square"></i> 135-5154-5661</span>#}
                {#                            </div>#}
                {#                        </div>#}
                {#                    </div>#}
                {#                </div>#}


            </div>
            <div id="factory_list_bar">
                {% include 'partinfo/page_bar.html' %}
            </div>

            <div class="modal fade" id="model_factory_add" style="display: none;">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span></button>
                            <h4 class="modal-title">添加信息</h4>
                        </div>
                        <div class="modal-body">

                            <form action="#" method="post" id="add_factory_form">
                                {% csrf_token %}
                                <div class="col-md-6">
                                    <div class="form-group">

                                        <label>工厂名称</label>
                                        <input type="text" class="form-control" name="txt_factory_name"
                                               id="txt_factory_name"
                                               placeholder="">

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">

                                        <label>联系人</label>
                                        <input type="text" class="form-control" name="txt_factory_contact"
                                               id="txt_factory_contact"
                                               placeholder="">

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>电话</label>
                                        <input type="text" class="form-control" name="txt_factory_phone_num"
                                               id="txt_factory_phone_num"
                                               placeholder="">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>QQ</label>
                                        <input type="text" class="form-control" name="txt_factory_qq"
                                               id="txt_factory_qq"
                                               placeholder="">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>联系地址</label>
                                        <input type="text" class="form-control" name="txt_factory_address"
                                               id="txt_factory_address"
                                               placeholder="">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>备注</label>
                                        <textarea class="form-control" rows="4" name="txt_area_factory_desc"
                                                  id="txt_area_factory_desc"
                                                  placeholder="....."></textarea>
                                    </div>
                                </div>

                            </form>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default pull-left" id="btn_factory_cancel"
                                    data-dismiss="modal">
                                <i class="fa fa-remove "> 取消</i></button>
                            <button type="submit" class="btn btn-primary" id="btn_factory_save"><i class="fa fa-check">
                                保存</i>
                            </button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>


        </div>
    </div>

{% endblock %}
{% block javascript %}
    <script src="{% static 'js/parts_factory_customer_model_select2.js' %}"></script>

    <script>
        $(document).ready(function () {
            getPageInfo(1);

            $("#btn_search").click(function () {
                getPageInfo(1);
            })
            $("#btn_search_txt_clear").click(function () {
                $("#search_key_word").val("");
                getPageInfo(1);
            })
            $("#btn_factory_save").click(function () {
                var txt_factory_name = $("#txt_factory_name");
                if (txt_factory_name.val() == "") {
                    txt_factory_name.parent().addClass("has-error");
                    toastr.error('工厂名称不能为空！');
                    return;
                }
                var txt_factory_contact = $("#txt_factory_contact");
                if (txt_factory_contact.val() == "") {
                    txt_factory_contact.val('---');
                }
                var txt_factory_qq = $("#txt_factory_qq");
                if (txt_factory_qq.val() == "") {
                    txt_factory_qq.val('xxxxxxxxx')
                }
                var txt_factory_phone_num = $("#txt_factory_phone_num");
                if (txt_factory_phone_num.val() == "") {
                    txt_factory_phone_num.val('xxx-xxxx-xxxx');
                }
                var txt_factory_address = $("#txt_factory_address");
                if (txt_factory_address.val() == "") {
                    txt_factory_address.val('暂无详细地址');
                }


                var factory_form_data = new FormData($("#add_factory_form")[0])

                $.ajax({
                    type: "POST",
                    url: "{% url 'partsinfo:add_factory_info' %}",
                    data: factory_form_data,
                    async: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {


                        if (data == "success") {
                            $('#model_factory_add').modal('hide');
                            toastr.success('添加成功！2333');
                            getPageInfo(1);
                        }
                        else if (data == 'info_exist') {

                            toastr.error('工厂名称重复');
                            $("#txt_factory_name").parent().addClass("has-error");
                        }
                        else {
                            toastr.error('添加失败 未知错误');
                        }

                    }

                });


            });

            $('#model_factory_add').on('hide.bs.modal', function () {

                $("#add_factory_form")[0].reset();

                var txt_factory_name = $("#txt_factory_name");
                if (txt_factory_name.parent().hasClass("has-error")) {
                    txt_factory_name.parent().removeClass("has-error");
                }

            });

        })


        function getPageInfo(page) {

            $.ajax({
                type: "GET",

                url: "{% url 'partsinfo:factory_list' %}?page=" + page + "&q=" + $("#search_key_word").val(),

                async: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    showFactoryInfo(data.factory_list);
                    initPageBar(data.page_info, "factory_list_bar", 'getPageInfo');

                }

            });
        }

        function showFactoryInfo(list) {
            var factory_list = $("#factory_list");
            factory_list.empty();
            for (var index in list) {
                var html = '<div class="col-md-3 col-sm-6 col-xs-12">\
                                         <div class="box box-widget">\
                                            <a style="color: #444;"  href="/baseinfo/factory_detail/' + list[index].pk + '">\
                                            <div class="box-header with-border">\
                                                 <span class="info-box-text" style="font-size:16px;">' + list[index].fields.name + '</span>\
                                             </div></a>\
                                             <div class="box-body">\
                                                 <div class="">\
                                                     <span class="text-muted"><i class="fa  fa-commenting-o"></i> ' + list[index].fields.Contact + '</span>\
                                                 </div>\
                                                 <div>\
                                                     <span class="text-muted" style="display: block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;"><i class="fa fa-tags"></i> ' + list[index].fields.address + '</span>\
                                                 </div>\
                                                 <div>\
                                                     <span class="text-muted pull-left"><i class="fa fa-qq"></i> ' + list[index].fields.qq + '</span>\
                                                     <span class="text-muted pull-right"><i class="fa fa-phone-square"></i> ' + list[index].fields.phone_num + '</span>\
                                                 </div>\
                                             </div>\
                                         </div>\
                                     </div>';
                factory_list.append(html);

            }
        }


    </script>
{% endblock %}

templates/partinfo/index.html
{% extends 'partinfo/base.html' %}
{% load static %}
{% block title %}index{% endblock %}
{% block content-header %} this is index{% endblock %}
{% block content %} index
{% endblock %}

templates/partinfo/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Ocean Login</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
  <!-- iCheck -->


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'partsinfo:index' %}"><b>O</b>cean</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg" style="color: red">{{ state }}</p>

    <form action="{% url 'partsinfo:login' %}" role="form" method="POST">
            {% csrf_token %}

        <div class="form-group has-feedback">
        <input type="text" class="form-control" name="username" placeholder="账号">
        <span class=" form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" name="password" placeholder="密码">
        <span class=" form-control-feedback"></span>
      </div>
      <div class="row">

        <!-- /.col -->
        <div class="col-xs-4 pull-right">
          <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
        </div>
        <!-- /.col -->
      </div>
    </form>


    <a href="#">忘记密码</a><br>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- iCheck -->

<script>

</script>
</body>
</html>

templates/partinfo/page_bar.html
<div class="box-footer" style="background-color: transparent">
    <small id="page_info"></small>

    <ul class="pagination pagination-sm no-margin pull-right" id="page_list">

    </ul>
</div>